import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/layout/Container";

export const metadata = {
  title: "Terms of Service | Namazing",
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="flex-1 py-16">
        <Container size="sm">
          <h1 className="font-display text-4xl text-studio-ink mb-8">Terms of Service</h1>
          <div className="prose prose-neutral max-w-none text-studio-ink/70 space-y-6">
            <p>
              <strong>Last updated:</strong> January 2026
            </p>
            <p>
              By using Namazing, you agree to these Terms of Service. Please read them carefully.
            </p>
            <h2 className="font-display text-2xl text-studio-ink mt-8">Use of Service</h2>
            <p>
              Namazing provides AI-powered baby name consultation services. You may use the service
              for personal, non-commercial purposes. You must be at least 13 years old to create an account.
            </p>
            <h2 className="font-display text-2xl text-studio-ink mt-8">Account Responsibility</h2>
            <p>
              You are responsible for maintaining the security of your account credentials. You agree
              not to share your account access with others.
            </p>
            <h2 className="font-display text-2xl text-studio-ink mt-8">Content</h2>
            <p>
              Name recommendations are generated by AI and provided for informational purposes. We do
              not guarantee the accuracy, completeness, or suitability of any name suggestion.
            </p>
            <h2 className="font-display text-2xl text-studio-ink mt-8">Limitation of Liability</h2>
            <p>
              Namazing is provided &quot;as is&quot; without warranties of any kind. We are not liable
              for any damages arising from your use of the service.
            </p>
            <h2 className="font-display text-2xl text-studio-ink mt-8">Contact</h2>
            <p>
              For questions about these Terms, contact us at legal@namazing.com.
            </p>
          </div>
        </Container>
      </main>
      <Footer />
    </>
  );
}
