import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/layout/Container";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using the Namazing baby name consultation service.",
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="flex-1 py-16">
        <Container size="md">
          <h1 className="font-display text-4xl text-studio-ink mb-2">Terms of Service</h1>
          <p className="text-sm text-studio-ink/50 mb-10">Last updated: February 6, 2026</p>

          <div className="prose prose-neutral max-w-none space-y-8 text-studio-ink/80">
            <section>
              <h2 className="font-display text-xl text-studio-ink">1. Acceptance of terms</h2>
              <p>
                By accessing or using Namazing (&ldquo;the Service&rdquo;), you agree to be bound by these
                Terms of Service. If you do not agree, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl text-studio-ink">2. Description of service</h2>
              <p>
                Namazing is an AI-powered baby name consultation service. We use artificial
                intelligence to generate personalized name recommendations based on your preferences.
                The Service is provided for informational and entertainment purposes.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl text-studio-ink">3. Accounts</h2>
              <p>
                You must sign in with a Google account to use the Service. You are responsible for
                maintaining the security of your account. You must be at least 18 years old to create
                an account.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl text-studio-ink">4. Usage limits</h2>
              <p>
                The Service may impose limits on usage, including the number of naming consultations
                per day. These limits may change at our discretion. We reserve the right to restrict
                or terminate access for users who abuse the Service.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl text-studio-ink">5. AI-generated content</h2>
              <p>
                Name recommendations and reports are generated by AI and are provided as suggestions
                only. We do not guarantee the accuracy, completeness, or suitability of any
                AI-generated content. You are solely responsible for any naming decisions you make.
              </p>
              <p>
                AI-generated content may occasionally contain errors, biases, or culturally
                insensitive suggestions despite our best efforts to prevent this. We encourage you to
                independently verify any information provided.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl text-studio-ink">6. Intellectual property</h2>
              <p>
                The Service, including its design, code, and branding, is owned by Namazing. The name
                recommendations and reports generated for you are yours to use freely.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl text-studio-ink">7. Limitation of liability</h2>
              <p>
                The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the
                maximum extent permitted by law, Namazing shall not be liable for any indirect,
                incidental, special, or consequential damages arising from your use of the Service.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl text-studio-ink">8. Termination</h2>
              <p>
                We may suspend or terminate your access to the Service at any time, with or without
                cause. You may delete your account at any time by contacting us.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl text-studio-ink">9. Changes to terms</h2>
              <p>
                We may update these terms from time to time. Continued use of the Service after
                changes constitutes acceptance of the updated terms.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl text-studio-ink">10. Contact</h2>
              <p>
                Questions about these terms? Contact us at{" "}
                <a href="mailto:hello@namazing.co" className="text-studio-terracotta hover:underline">
                  hello@namazing.co
                </a>
                .
              </p>
            </section>
          </div>
        </Container>
      </main>
      <Footer />
    </>
  );
}
